name: 'Integration Tests'
on:
  schedule:
    - cron: 0/5 * * * *
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    outputs:
      playwright_success: ${{ steps.playwright.outputs.success }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - id: playwright
        if: success()
        run: echo "success=yes" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30"
      - if: ${{ steps.playwright.outputs.success!='yes' }}
        run: |
          exit 1
  badge:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: use data
        run: |
          echo "This works ${{ needs.test.outputs.playwright_success }}"
          echo "Not works ${{ needs.test.outputs.success }}"
          echo "Works3 ${{ needs.test.steps.playwright.outputs.success }}"
      - id: echo1
        if: ${{ needs.test.outputs.playwright_success=='yes' }}
        run: echo "test success"
      - id: echo2
        if: ${{ needs.test.outputs.playwright_success!='yes' }}
        run: |
          echo "test fail"
          exit 1
